POST http://localhost:9080/transactions
Content-Type: application/json

{
  "transaction": {
    "originId": "191003",
    "destinationId": "191002",
    "amount": 7,
    "created": "2022-05-10T23:13:00-05:00",
    "transactionId": "7",
    "channel": "NHBK"
  }
}
